// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: appgate.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayControlPlane_StreamConfig_FullMethodName       = "/appgate.GatewayControlPlane/StreamConfig"
	GatewayControlPlane_Heartbeat_FullMethodName          = "/appgate.GatewayControlPlane/Heartbeat"
	GatewayControlPlane_ReportAudit_FullMethodName        = "/appgate.GatewayControlPlane/ReportAudit"
	GatewayControlPlane_RequestCertificate_FullMethodName = "/appgate.GatewayControlPlane/RequestCertificate"
)

// GatewayControlPlaneClient is the client API for GatewayControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayControlPlane is the service that gateways use to connect to the control plane.
type GatewayControlPlaneClient interface {
	// StreamConfig opens a long-lived stream for config push and heartbeats.
	StreamConfig(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamConfigRequest, ConfigUpdate], error)
	// Heartbeat is called periodically by gateways to report health.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// ReportAudit sends batched audit events from gateways to the control plane.
	ReportAudit(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AuditEvent, AuditAck], error)
	// RequestCertificate allows gateways to request mTLS certificates.
	RequestCertificate(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
}

type gatewayControlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayControlPlaneClient(cc grpc.ClientConnInterface) GatewayControlPlaneClient {
	return &gatewayControlPlaneClient{cc}
}

func (c *gatewayControlPlaneClient) StreamConfig(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamConfigRequest, ConfigUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayControlPlane_ServiceDesc.Streams[0], GatewayControlPlane_StreamConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConfigRequest, ConfigUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayControlPlane_StreamConfigClient = grpc.BidiStreamingClient[StreamConfigRequest, ConfigUpdate]

func (c *gatewayControlPlaneClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, GatewayControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayControlPlaneClient) ReportAudit(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AuditEvent, AuditAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayControlPlane_ServiceDesc.Streams[1], GatewayControlPlane_ReportAudit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuditEvent, AuditAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayControlPlane_ReportAuditClient = grpc.ClientStreamingClient[AuditEvent, AuditAck]

func (c *gatewayControlPlaneClient) RequestCertificate(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, GatewayControlPlane_RequestCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayControlPlaneServer is the server API for GatewayControlPlane service.
// All implementations must embed UnimplementedGatewayControlPlaneServer
// for forward compatibility.
//
// GatewayControlPlane is the service that gateways use to connect to the control plane.
type GatewayControlPlaneServer interface {
	// StreamConfig opens a long-lived stream for config push and heartbeats.
	StreamConfig(grpc.BidiStreamingServer[StreamConfigRequest, ConfigUpdate]) error
	// Heartbeat is called periodically by gateways to report health.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// ReportAudit sends batched audit events from gateways to the control plane.
	ReportAudit(grpc.ClientStreamingServer[AuditEvent, AuditAck]) error
	// RequestCertificate allows gateways to request mTLS certificates.
	RequestCertificate(context.Context, *CertificateRequest) (*CertificateResponse, error)
	mustEmbedUnimplementedGatewayControlPlaneServer()
}

// UnimplementedGatewayControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayControlPlaneServer struct{}

func (UnimplementedGatewayControlPlaneServer) StreamConfig(grpc.BidiStreamingServer[StreamConfigRequest, ConfigUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamConfig not implemented")
}
func (UnimplementedGatewayControlPlaneServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedGatewayControlPlaneServer) ReportAudit(grpc.ClientStreamingServer[AuditEvent, AuditAck]) error {
	return status.Error(codes.Unimplemented, "method ReportAudit not implemented")
}
func (UnimplementedGatewayControlPlaneServer) RequestCertificate(context.Context, *CertificateRequest) (*CertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCertificate not implemented")
}
func (UnimplementedGatewayControlPlaneServer) mustEmbedUnimplementedGatewayControlPlaneServer() {}
func (UnimplementedGatewayControlPlaneServer) testEmbeddedByValue()                             {}

// UnsafeGatewayControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayControlPlaneServer will
// result in compilation errors.
type UnsafeGatewayControlPlaneServer interface {
	mustEmbedUnimplementedGatewayControlPlaneServer()
}

func RegisterGatewayControlPlaneServer(s grpc.ServiceRegistrar, srv GatewayControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedGatewayControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayControlPlane_ServiceDesc, srv)
}

func _GatewayControlPlane_StreamConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayControlPlaneServer).StreamConfig(&grpc.GenericServerStream[StreamConfigRequest, ConfigUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayControlPlane_StreamConfigServer = grpc.BidiStreamingServer[StreamConfigRequest, ConfigUpdate]

func _GatewayControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayControlPlaneServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayControlPlane_ReportAudit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayControlPlaneServer).ReportAudit(&grpc.GenericServerStream[AuditEvent, AuditAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayControlPlane_ReportAuditServer = grpc.ClientStreamingServer[AuditEvent, AuditAck]

func _GatewayControlPlane_RequestCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayControlPlaneServer).RequestCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayControlPlane_RequestCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayControlPlaneServer).RequestCertificate(ctx, req.(*CertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayControlPlane_ServiceDesc is the grpc.ServiceDesc for GatewayControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appgate.GatewayControlPlane",
	HandlerType: (*GatewayControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _GatewayControlPlane_Heartbeat_Handler,
		},
		{
			MethodName: "RequestCertificate",
			Handler:    _GatewayControlPlane_RequestCertificate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConfig",
			Handler:       _GatewayControlPlane_StreamConfig_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReportAudit",
			Handler:       _GatewayControlPlane_ReportAudit_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "appgate.proto",
}
