// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: appgate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamConfigRequest) Reset() {
	*x = StreamConfigRequest{}
	mi := &file_appgate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfigRequest) ProtoMessage() {}

func (x *StreamConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appgate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfigRequest.ProtoReflect.Descriptor instead.
func (*StreamConfigRequest) Descriptor() ([]byte, []int) {
	return file_appgate_proto_rawDescGZIP(), []int{0}
}

func (x *StreamConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StreamConfigRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StreamConfigRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Backends      []string               `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	Routes        []string               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_appgate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_appgate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_appgate_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigUpdate) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ConfigUpdate) GetBackends() []string {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *ConfigUpdate) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Metrics       *HeartbeatMetrics      `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_appgate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appgate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_appgate_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetMetrics() *HeartbeatMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type HeartbeatMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestsTotal uint64                 `protobuf:"varint,1,opt,name=requests_total,json=requestsTotal,proto3" json:"requests_total,omitempty"`
	ErrorsTotal   uint64                 `protobuf:"varint,2,opt,name=errors_total,json=errorsTotal,proto3" json:"errors_total,omitempty"`
	LatencyP99    float64                `protobuf:"fixed64,3,opt,name=latency_p99,json=latencyP99,proto3" json:"latency_p99,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMetrics) Reset() {
	*x = HeartbeatMetrics{}
	mi := &file_appgate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMetrics) ProtoMessage() {}

func (x *HeartbeatMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_appgate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMetrics.ProtoReflect.Descriptor instead.
func (*HeartbeatMetrics) Descriptor() ([]byte, []int) {
	return file_appgate_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatMetrics) GetRequestsTotal() uint64 {
	if x != nil {
		return x.RequestsTotal
	}
	return 0
}

func (x *HeartbeatMetrics) GetErrorsTotal() uint64 {
	if x != nil {
		return x.ErrorsTotal
	}
	return 0
}

func (x *HeartbeatMetrics) GetLatencyP99() float64 {
	if x != nil {
		return x.LatencyP99
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_appgate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appgate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_appgate_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_appgate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_appgate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_appgate_proto_rawDescGZIP(), []int{5}
}

func (x *AuditEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AuditEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AuditEvent) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AuditAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedCount int32                  `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAck) Reset() {
	*x = AuditAck{}
	mi := &file_appgate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAck) ProtoMessage() {}

func (x *AuditAck) ProtoReflect() protoreflect.Message {
	mi := &file_appgate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAck.ProtoReflect.Descriptor instead.
func (*AuditAck) Descriptor() ([]byte, []int) {
	return file_appgate_proto_rawDescGZIP(), []int{6}
}

func (x *AuditAck) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

type CertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CsrPem        string                 `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	CommonName    string                 `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_appgate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appgate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_appgate_proto_rawDescGZIP(), []int{7}
}

func (x *CertificateRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CertificateRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *CertificateRequest) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

type CertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	CaCertPem     string                 `protobuf:"bytes,2,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateResponse) Reset() {
	*x = CertificateResponse{}
	mi := &file_appgate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateResponse) ProtoMessage() {}

func (x *CertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appgate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateResponse.ProtoReflect.Descriptor instead.
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return file_appgate_proto_rawDescGZIP(), []int{8}
}

func (x *CertificateResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CertificateResponse) GetCaCertPem() string {
	if x != nil {
		return x.CaCertPem
	}
	return ""
}

func (x *CertificateResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_appgate_proto protoreflect.FileDescriptor

const file_appgate_proto_rawDesc = "" +
	"\n" +
	"\rappgate.proto\x12\aappgate\"`\n" +
	"\x13StreamConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"_\n" +
	"\fConfigUpdate\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12\x1a\n" +
	"\bbackends\x18\x02 \x03(\tR\bbackends\x12\x16\n" +
	"\x06routes\x18\x03 \x03(\tR\x06routes\"`\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x123\n" +
	"\ametrics\x18\x02 \x01(\v2\x19.appgate.HeartbeatMetricsR\ametrics\"}\n" +
	"\x10HeartbeatMetrics\x12%\n" +
	"\x0erequests_total\x18\x01 \x01(\x04R\rrequestsTotal\x12!\n" +
	"\ferrors_total\x18\x02 \x01(\x04R\verrorsTotal\x12\x1f\n" +
	"\vlatency_p99\x18\x03 \x01(\x01R\n" +
	"latencyP99\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"\xed\x01\n" +
	"\n" +
	"AuditEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1a\n" +
	"\bmetadata\x18\b \x01(\fR\bmetadata\"1\n" +
	"\bAuditAck\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x05R\racceptedCount\"g\n" +
	"\x12CertificateRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\tR\x06csrPem\x12\x1f\n" +
	"\vcommon_name\x18\x03 \x01(\tR\n" +
	"commonName\"o\n" +
	"\x13CertificateResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x1e\n" +
	"\vca_cert_pem\x18\x02 \x01(\tR\tcaCertPem\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt2\xac\x02\n" +
	"\x13GatewayControlPlane\x12G\n" +
	"\fStreamConfig\x12\x1c.appgate.StreamConfigRequest\x1a\x15.appgate.ConfigUpdate(\x010\x01\x12B\n" +
	"\tHeartbeat\x12\x19.appgate.HeartbeatRequest\x1a\x1a.appgate.HeartbeatResponse\x127\n" +
	"\vReportAudit\x12\x13.appgate.AuditEvent\x1a\x11.appgate.AuditAck(\x01\x12O\n" +
	"\x12RequestCertificate\x12\x1b.appgate.CertificateRequest\x1a\x1c.appgate.CertificateResponseB\"Z appgate-control-plane/pkg/api/pbb\x06proto3"

var (
	file_appgate_proto_rawDescOnce sync.Once
	file_appgate_proto_rawDescData []byte
)

func file_appgate_proto_rawDescGZIP() []byte {
	file_appgate_proto_rawDescOnce.Do(func() {
		file_appgate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appgate_proto_rawDesc), len(file_appgate_proto_rawDesc)))
	})
	return file_appgate_proto_rawDescData
}

var file_appgate_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_appgate_proto_goTypes = []any{
	(*StreamConfigRequest)(nil), // 0: appgate.StreamConfigRequest
	(*ConfigUpdate)(nil),        // 1: appgate.ConfigUpdate
	(*HeartbeatRequest)(nil),    // 2: appgate.HeartbeatRequest
	(*HeartbeatMetrics)(nil),    // 3: appgate.HeartbeatMetrics
	(*HeartbeatResponse)(nil),   // 4: appgate.HeartbeatResponse
	(*AuditEvent)(nil),          // 5: appgate.AuditEvent
	(*AuditAck)(nil),            // 6: appgate.AuditAck
	(*CertificateRequest)(nil),  // 7: appgate.CertificateRequest
	(*CertificateResponse)(nil), // 8: appgate.CertificateResponse
}
var file_appgate_proto_depIdxs = []int32{
	3, // 0: appgate.HeartbeatRequest.metrics:type_name -> appgate.HeartbeatMetrics
	0, // 1: appgate.GatewayControlPlane.StreamConfig:input_type -> appgate.StreamConfigRequest
	2, // 2: appgate.GatewayControlPlane.Heartbeat:input_type -> appgate.HeartbeatRequest
	5, // 3: appgate.GatewayControlPlane.ReportAudit:input_type -> appgate.AuditEvent
	7, // 4: appgate.GatewayControlPlane.RequestCertificate:input_type -> appgate.CertificateRequest
	1, // 5: appgate.GatewayControlPlane.StreamConfig:output_type -> appgate.ConfigUpdate
	4, // 6: appgate.GatewayControlPlane.Heartbeat:output_type -> appgate.HeartbeatResponse
	6, // 7: appgate.GatewayControlPlane.ReportAudit:output_type -> appgate.AuditAck
	8, // 8: appgate.GatewayControlPlane.RequestCertificate:output_type -> appgate.CertificateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_appgate_proto_init() }
func file_appgate_proto_init() {
	if File_appgate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appgate_proto_rawDesc), len(file_appgate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appgate_proto_goTypes,
		DependencyIndexes: file_appgate_proto_depIdxs,
		MessageInfos:      file_appgate_proto_msgTypes,
	}.Build()
	File_appgate_proto = out.File
	file_appgate_proto_goTypes = nil
	file_appgate_proto_depIdxs = nil
}
