# AppGate pre-commit hooks
# Install: pre-commit install
# Run all: pre-commit run --all-files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.18.0
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./"]

  - repo: https://github.com/dnephin/pre-commit-gofmt
    rev: v0.2.0
    hooks:
      - id: go-fmt
        files: 'control-plane/'

  - repo: https://github.com/DevinR528/cargo-fmt
    rev: v1.0.0
    hooks:
      - id: cargo-fmt
        files: 'gateway/'

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks