apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appgate-system
resources:
  - namespaces.yaml
  - rbac.yaml
  - control-plane.yaml
  - gateway.yaml
  - ../../../observability/prometheus/prometheus.yaml
  - ../../../observability/otel/otel-collector.yaml